package org.example.doublyLinkedList;

public class Main {
    public static void main(String[] args) {
        DoublyLinkedList myDLL = new DoublyLinkedList(1);
//        myDLL.getHead();
//        myDLL.getTail();
//        myDLL.getLength();
//        myDLL.append(12);
//        myDLL.append(14);
//        myDLL.append(16);
//        myDLL.printList();
//        myDLL.getLength();
//        DoublyLinkedList.Node removedNode =   myDLL.removeLast();
//        System.out.println("Removed Node: "  + removedNode.value);
//        myDLL.getLength();
//        myDLL.printList();
//        System.out.println("*************");
//        System.out.println(myDLL.removeLast().value);
//        System.out.println(myDLL.removeLast().value);
//        System.out.println(myDLL.removeLast().value);
//        System.out.println(myDLL.removeLast());
//        myDLL.prepend(8);
//        myDLL.append(12);
//        myDLL.append(14);
//        myDLL.append(16);
//        myDLL.append(18);
//        myDLL.getHead();
//        myDLL.getLength();
//        myDLL.printList();
//        System.out.println("*************");
//        System.out.println(myDLL.removeFirst().value);
//        System.out.println(myDLL.removeFirst().value);
//        System.out.println(myDLL.removeFirst().value);
//        System.out.println(myDLL.removeFirst());
//        myDLL.getLength();
//        DoublyLinkedList.Node node = myDLL.getNode(2);
//        System.out.println(node.value);
//        boolean isSet = myDLL.setNode(5, 19);
//        System.out.println(isSet);
//        myDLL.printList();
//        boolean isInserted = myDLL.insert(6, 15);
//        System.out.println("Is new node inserted: " + isInserted);
//        myDLL.printList();
//        DoublyLinkedList.Node removedNode = myDLL.remove(4);
//        System.out.println("Removed Node: " + removedNode.value);
//        myDLL.printList();
//        myDLL.append(7);
        myDLL.append(2);
//        myDLL.append(6);
//        myDLL.append(5);
        myDLL.append(3);
//        myDLL.append(4);
        myDLL.printList();
//        boolean isPalindrome = myDLL.isPalindrome();
//        System.out.println("Is the doubly linked list is palindrome: " + isPalindrome);
//        myDLL.reverse();
//        myDLL.printList();
        myDLL.partitionList(5);
        System.out.println("********");
        myDLL.printList();
    }
}
